#![cfg_attr(not(feature = "std"), no_std)]

extern crate alloc;

use alloc::vec::Vec;
use codec::{Decode, Encode};
use frame_support::pallet_prelude::*;
use frame_support::{BoundedVec, PalletId};
use frame_system::pallet_prelude::*;
use scale_info::TypeInfo;
use sp_io::hashing::blake2_256;
use sp_runtime::transaction_validity::{
	InvalidTransaction, TransactionSource, TransactionValidity, ValidTransaction,
};

/// Public inputs for an RWA purchase.
///
/// Phase 6 privacy model: `input_commitment`, `input_index`, `input_path`, and
/// `merkle_root` are REMOVED from public inputs.  The deposit-to-spend link is
/// broken by replacing them with a `spend_tag` that is derived from an ephemeral
/// ML-DSA-44 keypair generated by the wallet at deposit time:
///
///   spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes)
///
/// An on-chain observer sees `commitment` (in `DepositAccepted`) and `spend_tag`
/// (in `purchase_rwa` call data) — two different 32-byte values with no on-chain
/// link between them.  The deposit commitment is never present in purchase proofs.
#[derive(Encode, Decode, Clone, PartialEq, Eq, Debug, TypeInfo)]
pub struct RwaPurchaseInputs {
	/// Spend tag derived from the deposit-time ephemeral keypair.
	/// spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes)
	/// Registered on-chain at deposit via SpendTagValues.
	/// FIRST FIELD — SCALE encodes as bytes 0..32 (relied on by verify_purchase).
	pub spend_tag: [u8; 32],
	pub nullifier: [u8; 32],
	pub rwa_id: [u8; 32],
	pub destination: Vec<u8>, // 32-byte AccountId on the RWA chain
	pub tx_id: [u8; 16],
	/// A new private note representing RWA ownership.
	/// BLAKE3("nulla_rwa_ownership_v1" || rwa_id || blinding)
	pub ownership_commitment: [u8; 32],
}

pub trait ProofVerify {
	fn pedersen_check_u64(value: u64, blinding: [u8; 32], commitment: [u8; 32]) -> bool;
	fn verify_purchase(proof: &[u8], public_inputs: &[u8]) -> bool;
}

/// Trait implemented by the runtime to send an XCM `Transact` to the RWA
/// parachain whenever a `purchaseRwa` is accepted on the ProofHub chain.
///
/// The runtime wires this to `pallet_xcm::Pallet::send_xcm` targeting para 2001.
/// If the HRMP channel is not open yet the send silently fails (logged only) so
/// `purchase_rwa` itself never errors due to XCM delivery failure.
pub trait RwaPurchaseDispatch {
	fn send(
		rwa_id: [u8; 32],
		destination: Vec<u8>,
		nullifier: [u8; 32],
		spend_tag: [u8; 32],
		note_value: u64,
		tx_id: [u8; 16],
		ownership_commitment: [u8; 32],
	);
}

/// No-op implementation used when XCM is not wired (e.g. tests).
pub struct NoopRwaDispatch;
impl RwaPurchaseDispatch for NoopRwaDispatch {
	fn send(_: [u8; 32], _: Vec<u8>, _: [u8; 32], _: [u8; 32], _: u64, _: [u8; 16], _: [u8; 32]) {}
}

#[frame_support::pallet(dev_mode)]
pub mod pallet {
	use super::*;
	use frame_support::pallet_prelude::ConstU32;
	use frame_support::traits::{Currency, ExistenceRequirement};
	use sp_runtime::traits::UniqueSaturatedInto;

	#[pallet::pallet]
	pub struct Pallet<T>(_);

	#[pallet::config]
	pub trait Config: frame_system::Config {
		type RuntimeEvent: From<Event<Self>> + IsType<<Self as frame_system::Config>::RuntimeEvent>;
		type ProofVerifier: super::ProofVerify;
		type Currency: Currency<Self::AccountId>;
	// REMOVED: GenesisCommitments - faucet logic deprecated
	type PoolAccount: Get<<Self as frame_system::Config>::AccountId>;
	/// XCM dispatch: sends a `Transact` to the RWA parachain after a purchase.
	/// Use `NoopRwaDispatch` when XCM is not needed.
	type RwaDispatch: super::RwaPurchaseDispatch;
}

pub type BalanceOf<T> =
	<<T as Config>::Currency as Currency<<T as frame_system::Config>::AccountId>>::Balance;

#[pallet::storage]
#[pallet::getter(fn nullifier_used)]
pub type NullifierUsed<T: Config> =
	StorageMap<_, Blake2_128Concat, [u8; 32], bool, ValueQuery>;

#[pallet::storage]
#[pallet::getter(fn merkle_root)]
pub type MerkleRoot<T: Config> = StorageValue<_, [u8; 32], ValueQuery>;

#[pallet::storage]
#[pallet::getter(fn current_root)]
pub type CurrentRoot<T: Config> = StorageValue<_, [u8; 32], ValueQuery>;

#[pallet::storage]
#[pallet::getter(fn recent_roots)]
pub type RecentRoots<T: Config> =
	StorageValue<_, BoundedVec<[u8; 32], ConstU32<64>>, ValueQuery>;

	#[pallet::storage]
	#[pallet::getter(fn commitment_amounts)]
	pub type CommitmentAmounts<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], u64, ValueQuery>;

	/// Phase 6: Maps spend_tag → note value (registered at deposit time).
	/// spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes)
	/// The wallet provides this at deposit; it is unlinked from the commitment.
	#[pallet::storage]
	pub type SpendTagValues<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], u64, ValueQuery>;

	/// Phase 6: Guards against double-spend via the same spend_tag.
	/// A spend_tag can only be used once, regardless of the nullifier.
	#[pallet::storage]
	pub type SpendTagUsed<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], bool, ValueQuery>;

	/// RWA price registry: rwa_id → price in planck.
	/// Set by sudo. Zero means the RWA is not available for purchase.
	#[pallet::storage]
	#[pallet::getter(fn rwa_prices)]
	pub type RwaPrices<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], u64, ValueQuery>;

	#[pallet::storage]
	#[pallet::getter(fn genesis_initialized)]
	pub type GenesisInitialized<T: Config> = StorageValue<_, bool, ValueQuery>;

	#[pallet::storage]
	#[pallet::getter(fn leaves)]
	pub type Leaves<T: Config> =
		StorageValue<_, BoundedVec<[u8; 32], ConstU32<1048576>>, ValueQuery>;
		// Increased from 16384 to 1048576 (1M commitments = ~32MB storage)

	#[pallet::storage]
	#[pallet::getter(fn root_leaf_count)]
	pub type RootLeafCount<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], u32, ValueQuery>;

	#[pallet::storage]
	#[pallet::getter(fn commitment_index)]
	pub type CommitmentIndex<T: Config> =
		StorageMap<_, Blake2_128Concat, [u8; 32], u32, OptionQuery>;

	#[pallet::genesis_config]
	#[derive(frame_support::DefaultNoBound)]
	pub struct GenesisConfig<T: Config> {
		pub _phantom: core::marker::PhantomData<T>,
	}

	#[pallet::genesis_build]
	impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
		fn build(&self) {
			MerkleRoot::<T>::put([0u8; 32]);
			CurrentRoot::<T>::put([0u8; 32]);
			RecentRoots::<T>::put(BoundedVec::default());
			Leaves::<T>::put(BoundedVec::default());
			RootLeafCount::<T>::insert([0u8; 32], 0u32);
			// REMOVED: Faucet initialization - no longer needed
			GenesisInitialized::<T>::put(true);
		}
	}

	#[pallet::hooks]
	impl<T: Config> Hooks<BlockNumberFor<T>> for Pallet<T> {
		fn on_initialize(_n: BlockNumberFor<T>) -> Weight {
			// REMOVED: Faucet reinitialization logic
			if !GenesisInitialized::<T>::get() {
				GenesisInitialized::<T>::put(true);
			}
			Weight::zero()
		}
	}

	#[pallet::event]
	#[pallet::generate_deposit(pub(super) fn deposit_event)]
	pub enum Event<T: Config> {
		DepositAccepted {
			commitment: [u8; 32],
			/// Phase 6: spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes).
			/// Registered on-chain so it can be looked up at purchase time.
			/// Unlinkable from `commitment` to an outside observer.
			spend_tag: [u8; 32],
			amount: u64,
			new_merkle_root: [u8; 32],
			hints_blob: BoundedVec<u8, ConstU32<4096>>,
		},
		/// A private note was successfully used to authorise an RWA purchase.
		RwaPurchaseAuthorized {
			rwa_id: [u8; 32],
			destination: Vec<u8>,
			amount: u64,
			tx_id: [u8; 16],
		},
		/// Sudo set a new price for an RWA.
		RwaPriceSet { rwa_id: [u8; 32], price: u64 },
	}

	#[pallet::error]
	pub enum Error<T> {
		ProofVerificationFailed,
		NullifierAlreadyUsed,
		MlDsaFailed,
		/// The spend_tag was not registered at deposit time — deposit may not have occurred.
		SpendTagNotFound,
		/// This spend_tag has already been used in a previous purchase.
		SpendTagAlreadyUsed,
		/// The requested RWA has no price set — not available for purchase.
		RwaPriceNotSet,
		/// The note's deposited value is less than the RWA price.
		InsufficientFunds,
	}

	// Allow purchase_rwa as unsigned too
	#[pallet::validate_unsigned]
	impl<T: Config> ValidateUnsigned for Pallet<T> {
		type Call = Call<T>;

		fn validate_unsigned(_source: TransactionSource, call: &Self::Call) -> TransactionValidity {
			match call {
				Call::purchase_rwa { public_inputs, .. } => {
					if let Ok(inputs) = RwaPurchaseInputs::decode(&mut &public_inputs[..]) {
						if !SpendTagValues::<T>::contains_key(inputs.spend_tag) {
							return InvalidTransaction::Stale.into();
						}
						if SpendTagUsed::<T>::get(inputs.spend_tag) {
							return InvalidTransaction::Stale.into();
						}
						if NullifierUsed::<T>::get(inputs.nullifier) {
							return InvalidTransaction::Stale.into();
						}
						ValidTransaction::with_tag_prefix("RwaPurchase")
							.and_provides(inputs.tx_id)
							.and_provides(inputs.nullifier)
							.and_provides(inputs.spend_tag)
							.priority(100)
							.longevity(64)
							.propagate(true)
							.build()
					} else { InvalidTransaction::Call.into() }
				}
				_ => InvalidTransaction::Call.into(),
			}
		}
	}

	impl<T: Config> Pallet<T> {
		fn hash2(left: [u8; 32], right: [u8; 32]) -> [u8; 32] {
			let mut data = [0u8; 64];
			data[..32].copy_from_slice(&left);
			data[32..].copy_from_slice(&right);
			blake2_256(&data)
		}
		fn leaf_hash(commitment: [u8; 32]) -> [u8; 32] {
			let mut data = [0u8; 64];
			data[..32].copy_from_slice(&commitment);
			blake2_256(&data)
		}
		fn compute_merkle_root(leaves: &[[u8; 32]]) -> [u8; 32] {
			if leaves.is_empty() { return [0u8; 32]; }
			let mut level: alloc::vec::Vec<[u8; 32]> = leaves.to_vec();
			let zero = [0u8; 32];
			while level.len() & (level.len() - 1) != 0 { level.push(zero); }
			let mut cur = level;
			while cur.len() > 1 {
				let mut next = alloc::vec::Vec::with_capacity((cur.len() + 1) / 2);
				for pair in cur.chunks(2) {
					let a = pair[0];
					let b = if pair.len() == 2 { pair[1] } else { zero };
					next.push(Self::hash2(a, b));
				}
				cur = next;
			}
			cur[0]
		}
	}

	#[pallet::call]
	impl<T: Config> Pallet<T> {
		#[pallet::weight(Weight::zero())]
		pub fn deposit_public(
			origin: OriginFor<T>,
			commitment: alloc::vec::Vec<u8>,
			amount: u128,
			blinding: alloc::vec::Vec<u8>,
			// Phase 6: spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes)
			// Registered on-chain to enable unlinkable purchase later.
			spend_tag: [u8; 32],
			hints_blob: BoundedVec<u8, ConstU32<4096>>,
		) -> DispatchResult {
			let who = ensure_signed(origin)?;
			ensure!(commitment.len() == 32 && blinding.len() == 32, Error::<T>::ProofVerificationFailed);
			let mut c_arr = [0u8; 32]; c_arr.copy_from_slice(&commitment[..32]);
			let mut b_arr = [0u8; 32]; b_arr.copy_from_slice(&blinding[..32]);
			let amt_u64: u64 = amount.unique_saturated_into();
			ensure!(T::ProofVerifier::pedersen_check_u64(amt_u64, b_arr, c_arr), Error::<T>::ProofVerificationFailed);
			let pool = T::PoolAccount::get();
			let value: BalanceOf<T> = amount.unique_saturated_into();
			T::Currency::transfer(&who, &pool, value, ExistenceRequirement::KeepAlive)?;
			ensure!(!CommitmentIndex::<T>::contains_key(&c_arr), Error::<T>::ProofVerificationFailed);
			let mut leaves = Leaves::<T>::get();
			let leaf = Self::leaf_hash(c_arr);
			let idx = leaves.len() as u32;
			ensure!(leaves.try_push(leaf).is_ok(), Error::<T>::ProofVerificationFailed);
			CommitmentIndex::<T>::insert(&c_arr, idx);
			CommitmentAmounts::<T>::insert(&c_arr, amt_u64);
			// Phase 6: register spend_tag → value for unlinkable purchase lookup
			SpendTagValues::<T>::insert(spend_tag, amt_u64);
			let computed_root = Self::compute_merkle_root(&leaves);
			Leaves::<T>::put(leaves);
			let prev = CurrentRoot::<T>::get();
			CurrentRoot::<T>::put(computed_root);
			MerkleRoot::<T>::put(computed_root);
			let leaf_count = Leaves::<T>::get().len() as u32;
			RootLeafCount::<T>::insert(computed_root, leaf_count);
			let mut window = RecentRoots::<T>::get();
			if window.len() >= 64 {
				let mut shifted: BoundedVec<[u8; 32], ConstU32<64>> = BoundedVec::default();
				for i in 1..window.len() { let _ = shifted.try_push(window[i]); }
				window = shifted;
			}
			let _ = window.try_push(prev);
			RecentRoots::<T>::put(&window);
			Self::deposit_event(Event::DepositAccepted { commitment: c_arr, spend_tag, amount: amt_u64, new_merkle_root: computed_root, hints_blob });
			Ok(())
		}

		/// Spend a private note to purchase an RWA on the RWA appchain.
		///
		/// Phase 6 privacy model: `input_commitment` is no longer in public inputs.
		/// Instead, the wallet registers a `spend_tag` at deposit time:
		///   spend_tag = BLAKE3("nulla_spend_tag_v1" || deposit_pk_bytes)
		///
		/// The purchase proof = [deposit_pk (1312)] || [sig (2420)] where `sig` is
		/// an ML-DSA-44 signature over the public inputs using the deposit-time
		/// secret key.  On-chain verification checks:
		///   1. BLAKE3("nulla_spend_tag_v1" || proof_pk) == inputs.spend_tag
		///   2. ML-DSA-44 signature is valid
		///
		/// Privacy: an observer sees `commitment` in `DepositAccepted` and
		/// `spend_tag` in `purchase_rwa` — two different opaque values with no
		/// on-chain link.  The link can only be made by the wallet holding `deposit_sk`.
		#[pallet::weight(Weight::zero())]
		pub fn purchase_rwa(
			origin: OriginFor<T>,
			proof: Vec<u8>,
			public_inputs: Vec<u8>,
		) -> DispatchResult {
			ensure_none(origin)?;

			let inputs = RwaPurchaseInputs::decode(&mut &public_inputs[..])
				.map_err(|_| Error::<T>::ProofVerificationFailed)?;

			// Check nullifier has not been spent
			ensure!(!NullifierUsed::<T>::get(inputs.nullifier), Error::<T>::NullifierAlreadyUsed);

			// Phase 6: verify spend_tag was registered at deposit time
			ensure!(SpendTagValues::<T>::contains_key(inputs.spend_tag), Error::<T>::SpendTagNotFound);

			// Phase 6: verify spend_tag has not already been used
			ensure!(!SpendTagUsed::<T>::get(inputs.spend_tag), Error::<T>::SpendTagAlreadyUsed);

			// Look up note value via spend_tag (registered at deposit, commitment not needed)
			let note_value = SpendTagValues::<T>::get(inputs.spend_tag);

			// Check note value against RWA price
			let price = RwaPrices::<T>::get(inputs.rwa_id);
			ensure!(price > 0, Error::<T>::RwaPriceNotSet);
			ensure!(note_value >= price, Error::<T>::InsufficientFunds);

			// Verify ML-DSA-44 proof — includes spend_tag derivation check (Phase 6)
			ensure!(T::ProofVerifier::verify_purchase(&proof, &public_inputs), Error::<T>::MlDsaFailed);

			// Mark nullifier and spend_tag as used (double-spend prevention)
			NullifierUsed::<T>::insert(inputs.nullifier, true);
			SpendTagUsed::<T>::insert(inputs.spend_tag, true);

			Self::deposit_event(Event::RwaPurchaseAuthorized {
				rwa_id: inputs.rwa_id,
				destination: inputs.destination.clone(),
				amount: note_value,
				tx_id: inputs.tx_id,
			});

			// Phase 4: XCM — dispatch to RWA parachain (para 2001).
			// Phase 6: pass spend_tag instead of commitment (commitment stays private).
			T::RwaDispatch::send(
				inputs.rwa_id,
				inputs.destination,
				inputs.nullifier,
				inputs.spend_tag,
				note_value,
				inputs.tx_id,
				inputs.ownership_commitment,
			);

			Ok(())
		}

		/// Sudo: set the price (in planck) for an RWA.
		/// Setting price to 0 disables the RWA for purchase.
		#[pallet::weight(Weight::zero())]
		pub fn set_rwa_price(
			origin: OriginFor<T>,
			rwa_id: [u8; 32],
			price: u64,
		) -> DispatchResult {
			ensure_root(origin)?;
			RwaPrices::<T>::insert(rwa_id, price);
			Self::deposit_event(Event::RwaPriceSet { rwa_id, price });
			Ok(())
		}
	}
}

pub use pallet::*;

pub trait WeightInfo {}

pub mod weights {
	pub struct SubstrateWeight<T>(sp_std::marker::PhantomData<T>);
	impl<T> super::WeightInfo for SubstrateWeight<T> {}
}
